# Generated by Django 3.2.5 on 2021-07-28 00:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catering',
            name='reservation',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='api.reservation'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='ends_at',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='room',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='api.room'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='starts_at',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
